[project]
name = "opensdl-domain-physics"
version = "0.1.0a0"
description = "Physics domain models and extension schemas."
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
dependencies = [
  "opensdl-core"
]

[project.entry-points."opensdl.domain_packs"]
physics = "opensdl_domain_physics.pack:get_pack"

[build-system]
requires = ["setuptools>=84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
